# Generated by Django 5.1.2 on 2024-11-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='joined_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='type',
            field=models.CharField(choices=[('kids', 'بچگانه'), ('women', 'زنانه'), ('men', 'مردانه')], max_length=10),
        ),
    ]
