# Generated by Django 5.1.6 on 2025-02-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_joined_date_shoe_created_date_alter_shoe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('loafer', 'راحتی'), ('sport', 'ورزشی'), ('boot', 'بوت'), ('sandal', 'صندل و تابستانی'), ('leather', 'چرمی')], default='loafer', max_length=10),
        ),
    ]
