# Generated by Django 5.1.6 on 2025-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shoe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('loafer', 'راحتی'), ('sport', 'ورزشی'), ('boot', 'بوت'), ('sandal', 'صندل و تابستانی'), ('leather', 'چرمی'), ('classic', 'کلاسیک')], default='loafer', max_length=10),
        ),
    ]
