# Generated by Django 5.2.6 on 2025-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
