# Generated by Django 5.2.7 on 2025-11-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده، در حال پردازش'), ('shipped', 'در حال ارسال'), ('completed', 'انجام شده'), ('canceled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
