# Generated by Django 5.2.7 on 2025-11-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_delete_member_shoe_slug_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
