# Generated by Django 5.2.7 on 2025-11-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_created_date_shoe_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='slug',
        ),
    ]
